name: Update 3D Contributions
on:
  schedule:
    - cron: "0 18 * * *"  # Roda diariamente às 15h (horário de Brasília)
  workflow_dispatch:       # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: lucianomenezesjr  # 👈 SEU USERNAME AQUI!
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update 3D contributions"
          git push
